//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilitysSet
    {
        public int Id { get; set; }
        public int IdFirms { get; set; }
        public int IdCars { get; set; }
    
        public virtual CarsSet CarsSet { get; set; }
        public virtual FirmsSet FirmsSet { get; set; }
    }
}
