//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Auto_ProjectEntities2 : DbContext
    {
        public Auto_ProjectEntities2()
            : base("name=Auto_ProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilitysSet> AvailabilitysSet { get; set; }
        public virtual DbSet<CarsSet> CarsSet { get; set; }
        public virtual DbSet<FirmsSet> FirmsSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
